export enum Class {
  INVALID = 'Invalid',
  UNIVERSAL = 'UNIVERSAL',
  GUARDIAN = 'GUARDIAN',
  REVENANT = 'REVENANT',
  WARRIOR = 'WARRIOR',
  ENGINEER = 'ENGINEER',
  RANGER = 'RANGER',
  THIEF = 'THIEF',
  ELEMENTALIST = 'ELEMENTALIST',
  MESMER = 'MESMER',
  NECROMANCER = 'NECROMANCER',
}

export enum WeaponType {
  INVALID = 'Invalid',
  EMPTY_HANDED = 'EMPTY_HANDED',
  GREATSWORD = 'GREATSWORD',
  SWORD = 'SWORD',
  AXE = 'AXE',
  TORCH = 'TORCH',
  SCEPTER = 'SCEPTER',
  FOCUS = 'FOCUS',
  KIT_CONJURE = 'KIT_CONJURE',
  TOME = 'TOME',
}

export enum WeaponPosition {
  INVALID = 'Invalid',
  UNIVERSAL = 'UNIVERSAL',
  MAIN_AHND = 'MAIN_HAND',
  OFF_HAND = 'OFF_HAND',
  TWO_HANDED = 'TWO_HANDED',
}

export enum Effect {
  INVALID = 'Invalid',

  AEGIES = 'AEGIES',
  AlACRITY = 'ALACRITY',
  FURY = 'FURY',
  MIGHT = 'MIGHT',
  QUICKNESS = 'QUICKNESS',
  RESOLUTION = 'RESOLUTION',
  RESISTANCE = 'RESISTANCE',
  PROTECTION = 'PROTECTION',
  REGENERATION = 'REGENERATION',
  VIGOR = 'VIGOR',
  SWIFTNESS = 'SWIFTNESS',
  STABILITY = 'STABILITY',

  VULNERABILITY = 'VULNERABILITY',
  CRIPPLED = 'CRIPPLED',
  BURNING = 'BURNING',
  BLEEDING = 'BLEEDING',
  POISON = 'POISON',
  CONFUSION = 'CONFUSION',

  BINDING_BLADE = 'BINDING_BLADE',
  VIRTUE_OF_JUSTICE = 'VIRTUE_OF_JUSTICE',
  SYMBOLIC_AVENGER = 'SYMBOLIC_AVENGER',
  INSPIRING_VIRTUE = 'INSPIRING_VIRTUE',
  ASHES_OF_THE_JUST = 'ASHES_OF_THE_JUST',

  ARBITRARY_EFFECT = 'ARBITRARY_EFFECT',
}
